/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Rating {
  Again = 1,
  Hard = 2,
  Good = 3,
  Easy = 4
}
export declare class FSRS {
  constructor()
  schedule(card: Card, now: Date): ScheduledCards
}
export declare class ScheduledCards {
  selectCard(rating: Rating): Card
}
export declare class Card {
  constructor()
  log(): ReviewLog
}
export declare class ReviewLog {
  toString(): string
}
